### ISSUE TITLE
stuck in update loop + reboot - thunderbolt

### ISSUE THREAD

**Issue by koen84** [rtrouton/create_os_x_vm_install_dmg#1]
Awesome script.  Though the automatic updater causes an infinite loop of fetching the thunderbolt 1.2 update and rebooting, since said update downloads + "installs" + reboots, but somehow isn't really installed and seen again as available update.

I'll try to work around it by virtually unplugging the network cable and waiting an hour.

**Comment by rtrouton** [comment]
How is your VM qualifying for this update? If you have Thunderbolt peripherals that are being assigned to the VM, that may trigger this behavior. In that case, stop sharing and this update should no longer appear.

**Comment by koen84** [comment]
Not sure.  I assumed recent OSX version all come with thunderbolt drivers (that try to install security patches) ?

I don't have any thunderbolt peripherals and i'm unaware to anything thunderbolt being assigned to virtualbox / that VM.  I noticed the same behaviour a while back in a fresh Maverics VM, though then the only annoyance was that the app store kept saying there was an update available, which seemed to install without errors, but always kept as available update.

Current VM is a fresh Yosemite.

Maybe i'm saying / doing something stupid, after all, i'm a mac novice.

**Comment by rtrouton** [comment]
The Thunderbolt updates are generally firmware updates, which means that they're trying to update a piece of hardware. What is the VM running on? VMware Fusion? VMware ESXi?

If it's VMware Fusion, do you have a Thunderbolt display or are using Thunderbolt ethernet adapters?

**Comment by koen84** [comment]
Yes, it's firmware update 1.2, the only thing i could find is the same behaviour on a physical install, which was marked by apple as "known bug" (post dates from 2013).

It runs inside the latest virtualbox + extension pack.

Display is connected over HDMI, no additional ethernet adapters.  Physical ethernet says bus = PCI and physical thunderbolt says "no devices connected".

**Comment by rtrouton** [comment]
Ah, I just noticed that you mentioned that you were using this with VirtualBox. Unfortunately, VirtualBox doesn't support running OS X 10.7.x or later as a guest OS, so I never tested the installers created by this script with VBox:

https://www.virtualbox.org/wiki/Guest_OSes

For best results, I recommend using installers created by this script with either VMware's Fusion or ESXi virtualization solutions.

**Comment by koen84** [comment]
"Page last updated 2013-10-09"
Virtualbox itself gives me a specific option until OS X 10.9 (64 bit) a.k.a. Maverics, which seems indication enough that it's supported ?

Have you ever tested with XenServer of XCP ?

**Comment by rtrouton** [comment]
According to Oracle's listing, OS X 10.7.x or later are not listed as supported guest OSs:

http://www.oracle.com/technetwork/server-storage/virtualbox/support/index.html

XenServer officially does not support running OS X as a guest OS:

http://support.citrix.com/article/CTX125253

The virtualization solutions that I've tested have been VMware's Fusion and ESXi, running on Apple hardware. VMs which are hosted by those solutions are working fine with the installers generated by this script.

I have not tested VMware Workstation, as that virtualization solution generally will not run on Apple hardware. I have also not tested anything outside of VMware's virtualization solutions.
