### ISSUE TITLE
Can't create working El Capitan images on Mountain Lion.

### ISSUE THREAD

**Issue by dfear** [rtrouton/create_os_x_vm_install_dmg#3]
I am running 10.8.5. I am trying to create DMGs and ISOs of OS X 10.11.1_15B42.

I can run your script ok. It outputs a DMG file and a ISO file, as requested. I can mount both files. When I try to run "Install OS X 10.11" from either mounted image, I get the following error message:   

> To download and restore OS X, your computer's eligibility will be verified with Apple.
> 
> Then:
> Could not find installation information for this machine.
> Contact AppleCare.

Is creating working (mountable, installable and bootable) El Capitan images (esp. ISOs) just not possible on Mountain Lion?  

P.S. This is the 7th attempt to create an El Capitan iso, and none of the isos created fully work.

**Comment by rtrouton** [comment]
Are you using the .dmg and .iso files with VMware virtual machines? Or are you using them to install El Capitan on an actual Mac?

**Comment by dfear** [comment]
I am using them to install El Capitan on an actual Mac.

**Comment by rtrouton** [comment]
Ah, OK. This script is not intended to produce installation media for actual Macs and does not support doing so. It is soley intended to produce .dmg and .iso disk image files for use with VMware virtual machines.
